sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: GIFW7pn+uIiW9eM8/VxNJD9ySL+c/Y0CAKtFlIyu1X6tsH4RgUVpBbETcvEpBhsRAH5W6rETJh0FaE5IAxOzWuVGcvWd9EvNqrsU5CYA3Ib7/N7fiBCCMyvXFNeYWbIaLrXWhiO3Gdq2oFAWs5LLIfqMLw8D6INofOBPk0xs6IXUD9eEcKX7vcuHUV38o0fwrJLTnO5U92FAd0/5hA0a59xhD1psIICmvbgmUMvwbQJ7md5YdnSRYRkr8oj/9FIbtP0Bziu1IJEbGmaiMa9hYdFgPprJe9pC213aQIuIVi7fwAL2FvC7Fla9EAICDFO9A47G0O8i/bUJJbyXohrjUorv2oZWVP/C/kvRD3+APAjf2soef0TdMU27BoSmLvABSFy9FU0qebzSlW2LS8fRDS7k1HcDs6JEayyRKVnO0tc74+9q4NslT6BzOsqOsdihVFKKE7EmvbnnO84NRDO7XGAfOx3Rx36Dx2jVFVykagIh5xpKax3p+spq6Bx0xKwJIIDQJoEKY6y+gcaRCY4X9njrzt3aOeju7Po0xVvx2tBmSfxzVOk25Cz+3WtDgS7nbswkgkJwj4l5H492BJHKdQlnH19678zkQBiNUwndr7T90jtw51e95iFihJkPIRmKm61Ek4xXtsi7ZJ3KWdXEymWn31x/1uJfnYk60EQM79w=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Rise-of-the-Dutch-Republic-Volume-12-1567-part-I_4813
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy